# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - erg

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
          node-version-file: '.npmrc'
          cache: 'npm'
      - run: npm ci
      - run: echo "https://www.npmjs.com/package/registration-system:_authToken=${{ secrets.NPM_AUTH_TOKEN }}">${{ github.workspace }}/./npmrc
      - run: npm publish
      - run: npm publish
        env:
             NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
             NPM_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
             GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
